# citation Label - b5f0aa
- name: '📡duplicate'
  description: 'This issue or pull request already exists'
  color: 'f0dc59'
- name: '📡invalid'
  description: 'This issue or pull request is invalid'
  color: 'f0dc59'
- name: '📡wrong'
  description: 'This issue or pull request is wrong'
  color: 'f0dc59'
- name: '🙇ブロック解除申請'
  color: 'ff0026'
- name: '👮ブロック申請'
  color: 'ee9cff'
- name: '🔮workflow (gh-actions)'
  color: 'ee9cff'
- name: '💃no context'
  description: 'No Context, 内容が薄いもう少し詳しいものがほしいものに付与'
  color: 'f0dc59'
