name: labels

on:
  push:
    branch:
      - main
    paths:
    - '.github/labels.yaml'
    - '.github/workflows/labels.yaml'
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: label sync
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
